services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env # TODO Absolute path?
    depends_on:
      - wordpress
    configs:
      - source: nginx-nginx.conf
        target: /etc/nginx/nginx.conf


  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    container_name: wordpress
    restart: unless-stopped
    secrets:
      - admin_password
      - user_password
      - db_password
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env # TODO Absolute path?
    depends_on:
      - mariadb
    configs:
      - source: wordpress-php-fpm-conf.conf
        target: /etc/php/8.2/fpm/php-fpm.conf
      - source: wordpress-wp-config.php
        target: /var/www/html/wp-config.php
      - source: wordpress-www.conf
        target: /etc/php/8.2/fpm/pool.d/www.conf
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST} 
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password # TODO Confirm absolute path
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    container_name: mariadb
    restart: unless-stopped
    secrets: # TODO Incluir admin_password?
      - db_password
      - dbroot_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env # TODO Absolute path?
    configs:
      - source: mariadb-my.cnf
        target: /etc/mysql/my.cnf
      - source: mariadb-init.sql
        target: /etc/mysql/init.sql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password # TODO Confirm absolute path
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot_password # TODO Confirm absolute path

volumes:
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb

configs:
  nginx-nginx.conf:
    file: ./requirements/nginx/conf/nginx.conf
  wordpress-php-fpm-conf.conf:
    file: ./requirements/wordpress/conf/php-fpm.conf
  wordpress-wp-config.php:
    file: ./requirements/wordpress/conf/wp-config.php
  wordpress-www.conf:
    file: ./requirements/wordpress/conf/www.conf
  mariadb-my.cnf:
    file: ./requirements/mariadb/conf/my.cnf
  mariadb-init.sql:
    file: ./requirements/mariadb/conf/init.sql

secrets:
  admin_password:
    file: ../secrets/admin.txt # TODO Confirm absolute path
  user_password:
    file: ../secrets/credentials.txt # TODO Confirm absolute path
  db_password:
    file: ../secrets/db_password.txt # TODO Confirm absolute path
  dbroot_password:
    file: ../secrets/dbroot_password.txt # TODO Confirm absolute path

networks:
  inception:
    name: inception
    driver: bridge

# TODO Confirmar que os RUN dos dockerfile ainda são compatíveis com debian 12
# TODO Ver PHP e FPM
# TODO Ficheiro .env e pasta secrets --> Paths absolutos
# TODO estudar isto do site wordpress