services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    configs:
      - source: nginx-nginx.conf
        target: /etc/nginx/nginx.conf


  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    container_name: wordpress
    restart: unless-stopped
    secrets:
      - admin_password
      - user_password
      - db_password
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    configs:
      - source: wordpress-php-fpm-conf.conf
        target: /etc/php/8.2/fpm/php-fpm.conf
      - source: wordpress-wp-config.php
        target: /var/www/html/wp-config.php
      - source: wordpress-www.conf
        target: /etc/php/8.2/fpm/pool.d/www.conf
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST} 
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    container_name: mariadb
    restart: unless-stopped
    secrets:
      - db_password
      - dbroot_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    configs:
      - source: mariadb-my.cnf
        target: /etc/mysql/my.cnf
      - source: mariadb-init.sql
        target: /etc/mysql/init.sql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot_password

volumes:
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb

configs:
  nginx-nginx.conf:
    file: ./requirements/nginx/conf/nginx.conf
  wordpress-php-fpm-conf.conf:
    file: ./requirements/wordpress/conf/php-fpm.conf
  wordpress-wp-config.php:
    file: ./requirements/wordpress/conf/wp-config.php
  wordpress-www.conf:
    file: ./requirements/wordpress/conf/www.conf
  mariadb-my.cnf:
    file: ./requirements/mariadb/conf/my.cnf
  mariadb-init.sql:
    file: ./requirements/mariadb/conf/init.sql

secrets:
  admin_password:
    file: ../secrets/admin.txt
  user_password:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  dbroot_password:
    file: ../secrets/dbroot_password.txt

networks:
  inception:
    name: inception
    driver: bridge

# TODO Ver PHP e FPM
# TODO estudar isto do site wordpress
# TODO How Docker and docker-compose work
# TODO Difference between docker image used with docker-compose and without docker-compose
# TODO docker-compose ps (-p)?
# TODO ssh for the VM
# "docker stop $(docker ps -qa); docker rm $(docker ps -qa); docker rmi -f $(docker images -qa); docker volume rm $(docker volume ls -q); docker network rm $(docker network ls -q) 2>/dev/null"
# TODO login to the database. "Try to login into the SQL database as root but with no password. If the login is successful, the evaluation process ends now"
# TODO easier reboot?